{
 "title": "Sample App",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[10s]) ) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[10s])/10",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(delta(http_request_duration_seconds_sum[10s]) ) by (method, path) / sum(delta(http_request_duration_seconds_count[10s]) ) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Active Handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_active_handles", "legendFormat": "{{instance}} {{type}}" }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_active_requests", "legendFormat": "{{instance}} {{type}}" }
   ]
  }
 ]
}